// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';

// Export a plain config object. Some Prisma package entry-points used by
// generated `prisma.config.ts` may not be available in this environment,
// so keep the config shape simple and compatible with the Prisma CLI.
export default {
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
};
